#---------------------------------------------------------------------
# using pre-processor CPP (GNU GCC)
# for alias register names 
# do not change
# r0, r1, r2, r8 are used by ecalls

# forth struct pointer, constant 
#define usr r7

# instruction pointer, preserved
#define ipt r6

# memory index 
#define idx r0

# hash value
#define hsh r1

# link pointer
#define lnk r2

# word pointer
#define wrd r3

# generic
#define fst r4

# generic
#define snd r5

